(in-package :su-real)
;; @author Luca Krohm
(def-fact-group suturo-plans (desig:action-grounding)
  ;; @author Luca Krohm
  (<- (action-grounding ?designator (su-real:pick-up ?resolved-action-designator))
    (spec:property ?designator (:type :picking-up))
    (once (or (desig:desig-prop ?designator (:collision-mode ?collision-mode))
              (equal ?collision-mode nil)))
    (once (or (desig:desig-prop ?designator (:collision-object-b ?collision-object-b))
              (equal ?collision-object-b nil)))
    (once (or (desig:desig-prop ?designator (:collision-object-b-link
                                             ?collision-object-b-link))
              (equal ?collision-object-b-link nil)))
    (once (or (desig:desig-prop ?designator (:collision-object-a ?collision-object-a))
              (equal ?collision-object-a nil)))
    (once (or (desig:desig-prop ?designator (:move-base ?move-base))
              (equal ?move-base nil)))
    (once (or (desig:desig-prop ?designator (:prefer-base ?prefer-base))
              (equal ?prefer-base nil)))
    (once (or (desig:desig-prop ?designator (:straight-line ?straight-line))
              (equal ?straight-line nil)))
    (once (or (desig:desig-prop ?designator (:align-planes-left ?align-planes-left))
              (equal ?align-planes-left nil)))
    (once (or (desig:desig-prop ?designator (:align-planes-right ?align-planes-right))
              (equal ?align-planes-right nil)))
    (once (or (desig:desig-prop ?designator (:precise-tracking ?precise-tracking))
              (equal ?precise-tracking nil)))
    (once (or (desig:desig-prop ?designator (:object-pose ?object-pose))
              (equal ?object-pose nil)))
    (once (or (desig:desig-prop ?designator (:object-size ?object-size))
              (equal ?object-size nil)))

    (desig:designator :action ((:type :picking-up)
                               (:collision-mode ?collision-mode)
                               (:collision-object-b ?collision-object-b)
                               (:collision-object-b-link ?collision-object-b-link)
                               (:collision-object-a ?collision-object-a)
                               (:move-base ?move-base)
                               (:prefer-base ?prefer-base)
                               (:align-planes-left ?align-planes-left)
                               (:align-planes-right ?align-planes-right)
                               (:straight-line ?straight-line)
                               (:precise-tracking ?precise-tracking)
                               (:object-pose ?object-pose)
                               (:object-size ?object-size))
                      ?resolved-action-designator))

  ;; @author Luca Krohm
  (<- (action-grounding ?designator (su-real:place ?resolved-action-designator))
    (spec:property ?designator (:type :placing))
    (once (or (desig:desig-prop ?designator (:collision-mode ?collision-mode))
              (equal ?collision-mode nil)))
    (once (or (desig:desig-prop ?designator (:collision-object-b ?collision-object-b))
              (equal ?collision-object-b nil)))
    (once (or (desig:desig-prop ?designator (:collision-object-b-link
                                             ?collision-object-b-link))
              (equal ?collision-object-b-link nil)))
    (once (or (desig:desig-prop ?designator (:collision-object-a ?collision-object-a))
              (equal ?collision-object-a nil)))
    (once (or (desig:desig-prop ?designator (:move-base ?move-base))
              (equal ?move-base nil)))
    (once (or (desig:desig-prop ?designator (:prefer-base ?prefer-base))
              (equal ?prefer-base nil)))
    (once (or (desig:desig-prop ?designator (:straight-line ?straight-line))
              (equal ?straight-line nil)))
    (once (or (desig:desig-prop ?designator (:align-planes-left ?align-planes-left))
              (equal ?align-planes-left nil)))
    (once (or (desig:desig-prop ?designator (:align-planes-right ?align-planes-right))
              (equal ?align-planes-right nil)))
    (once (or (desig:desig-prop ?designator (:precise-tracking ?precise-tracking))
              (equal ?precise-tracking nil)))
    (once (or (desig:desig-prop ?designator (:target-pose ?target-pose))
              (equal ?target-pose nil)))
    (once (or (desig:desig-prop ?designator (:object-height ?object-height))
              (equal ?object-height nil)))

    (desig:designator :action ((:type :placing)
                               (:collision-mode ?collision-mode)
                               (:collision-object-b ?collision-object-b)
                               (:collision-object-b-link ?collision-object-b-link)
                               (:collision-object-a ?collision-object-a)
                               (:move-base ?move-base)
                               (:prefer-base ?prefer-base)
                               (:align-planes-left ?align-planes-left)
                               (:align-planes-right ?align-planes-right)
                               (:straight-line ?straight-line)
                               (:precise-tracking ?precise-tracking)
                               (:target-pose ?target-pose)
                               (:object-height ?object-height))
                      ?resolved-action-designator))

  )
                                                    
  
